# Table of Contents
 <p><div class="lev1"><a href="#Task-1.-Compiling-Ebola-Data"><span class="toc-item-num">Task 1.&nbsp;&nbsp;</span>Compiling Ebola Data</a></div>
 <div class="lev1"><a href="#Task-2.-RNA-Sequences"><span class="toc-item-num">Task 2.&nbsp;&nbsp;</span>RNA Sequences</a></div>
 <div class="lev1"><a href="#Task-3.-Class-War-in-Titanic"><span class="toc-item-num">Task 3.&nbsp;&nbsp;</span>Class War in Titanic</a></div></p>

In [1]:
DATA_FOLDER = 'Data' # Use the data folder provided in Tutorial 02 - Intro to Pandas.

In [2]:
import pandas as pd

## Task 1. Compiling Ebola Data

The `DATA_FOLDER/ebola` folder contains summarized reports of Ebola cases from three countries (Guinea, Liberia and Sierra Leone) during the recent outbreak of the disease in West Africa. For each country, there are daily reports that contain various information about the outbreak in several cities in each country.

Use pandas to import these data files into a single `Dataframe`.
Using this `DataFrame`, calculate for *each country*, the *daily average per month* of *new cases* and *deaths*.
Make sure you handle all the different expressions for *new cases* and *deaths* that are used in the reports.

In [3]:
import os

'''
    We load the data using a directory name, the columns to keep, the column to interpret as a date, 
    the new columns name, and which country the data correspond to
'''
def load_ebola_data_from_dir(directory, columns, date_columns, columns_new_names, country):
    tmp_dfs = [pd.read_csv(os.path.join(directory, filename), 
                          usecols=columns, 
                          parse_dates=date_columns) for filename in os.listdir(directory)]
    
    return pd.concat(tmp_dfs).rename(columns = lambda x : columns_new_names[columns.index(x)]).assign(Country=country)

'''
    Compute the average of the variable in the list given in parameter.
    The average is given per day for every month and country.
'''
def calculate_average(list_columns):
    filtered_e_data = e_data[e_data.Description.isin(list_columns)].dropna()

    filtered_e_data.loc[:, "Totals"] = filtered_e_data.Totals.apply(pd.to_numeric)

    totals_per_country_per_month = filtered_e_data.groupby(["Country", filtered_e_data.Date.dt.month])[["Totals"]].sum()
    
    return totals_per_country_per_month.apply(lambda x : x / 30.)

    
EBOLA_DATA_FOLDER = os.path.join(DATA_FOLDER, "ebola")
GUINEA_DATA_FOLDER = os.path.join(EBOLA_DATA_FOLDER, "guinea_data")
LIBERIA_DATA_FOLDER = os.path.join(EBOLA_DATA_FOLDER, "liberia_data")
SIERRA_DATA_FOLDER = os.path.join(EBOLA_DATA_FOLDER, "sl_data")

EBOLA_COLUMNS_NAMES = ["Date", "Description", "Totals"]
guinea_data = load_ebola_data_from_dir(GUINEA_DATA_FOLDER, ["Date", "Description", "Totals"], ["Date"], EBOLA_COLUMNS_NAMES, "Guinea")
liberia_data = load_ebola_data_from_dir(LIBERIA_DATA_FOLDER, ["Date", "Variable", "National"], ["Date"], EBOLA_COLUMNS_NAMES, "Liberia")
sierra_data = load_ebola_data_from_dir(SIERRA_DATA_FOLDER, ["date", "variable", "National"], ["date"], EBOLA_COLUMNS_NAMES, "Sierra")

# We appned all the dataframes together
e_data = guinea_data.append(liberia_data).append(sierra_data)

# These are the selected Description that contribute to our average.
new_case_columns = ["New cases of confirmed", "New case/s (confirmed)", "new_confirmed"]
new_death_columns = ["New deaths registered today", "Newly reported deaths", "etc_new_deaths"]

In [4]:
# Display the average for the new cases
calculate_average(new_case_columns)

                  Totals
Country Date
Guinea  8       2.066667
        9       6.933333
        10      0.200000
Liberia 6       0.500000
        7       0.666667
        8       1.633333
        9       4.933333
        10      1.133333
        11      1.300000
        12    578.500000
Sierra  8      12.366667
        9      33.266667
        10     52.933333
        11     41.933333
        12      5.433333

In [5]:
# Display the average for new deaths
calculate_average(new_death_columns)

                 Totals
Country Date
Guinea  8      0.066667
Liberia 6      0.466667
        7      1.566667
        8      6.966667
        9     28.833333
        10    23.366667
        11     6.733333
Sierra  9      0.266667
        10     3.300000
        11     0.400000
        12     0.366667

## Task 2. RNA Sequences

In the `DATA_FOLDER/microbiome` subdirectory, there are 9 spreadsheets of microbiome data that was acquired from high-throughput RNA sequencing procedures, along with a 10<sup>th</sup> file that describes the content of each. 

Use pandas to import the first 9 spreadsheets into a single `DataFrame`.
Then, add the metadata information from the 10<sup>th</sup> spreadsheet as columns in the combined `DataFrame`.
Make sure that the final `DataFrame` has a unique index and all the `NaN` values have been replaced by the tag `unknown`.

### Solution

First, we need to open and read from each file of data. we set the "header" parameter to None because there are no header in those files. And we group them into a list of frames to be able to iterate on them.

In [9]:
# Write your answer here

#open the 9 files
mb1 = pd.read_excel(DATA_FOLDER+'/microbiome/MID1.xls', sheetname='Sheet 1', header=None)
mb2 = pd.read_excel(DATA_FOLDER+'/microbiome/MID2.xls', sheetname='Sheet 1', header=None)
mb3 = pd.read_excel(DATA_FOLDER+'/microbiome/MID3.xls', sheetname='Sheet 1', header=None)
mb4 = pd.read_excel(DATA_FOLDER+'/microbiome/MID4.xls', sheetname='Sheet 1', header=None)
mb5 = pd.read_excel(DATA_FOLDER+'/microbiome/MID5.xls', sheetname='Sheet 1', header=None)
mb6 = pd.read_excel(DATA_FOLDER+'/microbiome/MID6.xls', sheetname='Sheet 1', header=None)
mb7 = pd.read_excel(DATA_FOLDER+'/microbiome/MID7.xls', sheetname='Sheet 1', header=None)
mb8 = pd.read_excel(DATA_FOLDER+'/microbiome/MID8.xls', sheetname='Sheet 1', header=None)
mb9 = pd.read_excel(DATA_FOLDER+'/microbiome/MID9.xls', sheetname='Sheet 1', header=None)

frames = [mb1,mb2,mb3,mb4,mb5,mb6,mb7,mb8,mb9]

ImportError: No module named 'xlrd'

Then, for each frame, we add a column with the index "BARCODE" to be able to recognize which lines belong to which file we read and to merge it easily with the metadata which has a column "BARCODE" that rely on the data files

In [8]:
i = 1
for f in frames:
    f['BARCODE'] = 'MID'+str(i)
    i+=1

NameError: name 'frames' is not defined

We can then concatenate the 9 DataFrame to get only one big resulting DataFrame. We have to set the "ignore_index" parameter to True to avoid duplicate indexes.

In [43]:
mb = pd.concat(frames, ignore_index=True)

After that we can read the metadata from the metadata.xls file and store it into a DataFrame

In [46]:
metadata = pd.read_excel(DATA_FOLDER+'/microbiome/metadata.xls', header=0)

And the last thing we need to do is to merge the two DataFrames on the column "BARCODE" to get one final DataFrame.

We also need to replace the NaN values by "unknown"

In [48]:
result = pd.merge(mb, metadata, on='BARCODE').fillna('unknown')
result

,0,1,BARCODE,GROUP,SAMPLE
0,"Archaea ""Crenarchaeota"" Thermoprotei Desulfuro...",7,MID1,EXTRACTION CONTROL,unknown
1,"Archaea ""Crenarchaeota"" Thermoprotei Desulfuro...",2,MID1,EXTRACTION CONTROL,unknown
2,"Archaea ""Crenarchaeota"" Thermoprotei Sulfoloba...",3,MID1,EXTRACTION CONTROL,unknown
3,"Archaea ""Crenarchaeota"" Thermoprotei Thermopro...",3,MID1,EXTRACTION CONTROL,unknown
4,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",7,MID1,EXTRACTION CONTROL,unknown
5,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",1,MID1,EXTRACTION CONTROL,unknown
6,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",1,MID1,EXTRACTION CONTROL,unknown
7,"Archaea ""Euryarchaeota"" Archaeoglobi Archaeogl...",1,MID1,EXTRACTION CONTROL,unknown
8,"Archaea ""Euryarchaeota"" Archaeoglobi Archaeogl...",1,MID1,EXTRACTION CONTROL,unknown
9,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",1,MID1,EXTRACTION CONTROL,unknown
10,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",4,MID1,EXTRACTION CONTROL,unknown
11,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",1,MID1,EXTRACTION CONTROL,unknown
12,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",2,MID1,EXTRACTION CONTROL,unknown
13,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",4,MID1,EXTRACTION CONTROL,unknown
14,"Archaea ""Euryarchaeota"" Methanococci Methanoco...",1,MID1,EXTRACTION CONTROL,unknown
15,"Archaea ""Euryarchaeota"" Methanopyri Methanopyr...",12,MID1,EXTRACTION CONTROL,unknown
16,"Archaea ""Euryarchaeota"" Thermoplasmata Thermop...",2,MID1,EXTRACTION CONTROL,unknown
17,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,MID1,EXTRACTION CONTROL,unknown
18,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,MID1,EXTRACTION CONTROL,unknown
19,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,MID1,EXTRACTION CONTROL,unknown
20,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,MID1,EXTRACTION CONTROL,unknown
21,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,MID1,EXTRACTION CONTROL,unknown
22,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",53,MID1,EXTRACTION CONTROL,unknown
23,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,MID1,EXTRACTION CONTROL,unknown
24,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,MID1,EXTRACTION CONTROL,unknown
25,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",3,MID1,EXTRACTION CONTROL,unknown
26,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,MID1,EXTRACTION CONTROL,unknown
27,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",99,MID1,EXTRACTION CONTROL,unknown
28,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",17,MID1,EXTRACTION CONTROL,unknown
29,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,MID1,EXTRACTION CONTROL,unknown
...,...,...,...,...,...
2366,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",10,MID9,Control 2,stool
2367,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2368,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2369,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2370,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",12,MID9,Control 2,stool
2371,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",4,MID9,Control 2,stool
2372,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",805,MID9,Control 2,stool
2373,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",862,MID9,Control 2,stool
2374,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",12,MID9,Control 2,stool
2375,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3534,MID9,Control 2,stool
2376,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",4,MID9,Control 2,stool
2377,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2378,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",25,MID9,Control 2,stool
2379,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,MID9,Control 2,stool
2380,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3,MID9,Control 2,stool
2381,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,MID9,Control 2,stool
2382,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2383,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3,MID9,Control 2,stool
2384,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,MID9,Control 2,stool
2385,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,MID9,Control 2,stool
2386,"Bacteria ""Synergistetes"" Synergistia Synergist...",3,MID9,Control 2,stool
2387,"Bacteria ""Tenericutes"" Mollicutes Anaeroplasma...",1,MID9,Control 2,stool
2388,"Bacteria ""Tenericutes"" Mollicutes Haloplasmata...",11,MID9,Control 2,stool
2389,"Bacteria ""Thermodesulfobacteria"" Thermodesulfo...",1,MID9,Control 2,stool
2390,"Bacteria ""Thermodesulfobacteria"" Thermodesulfo...",1,MID9,Control 2,stool
2391,"Bacteria ""Thermotogae"" Thermotogae Thermotogal...",43,MID9,Control 2,stool
2392,"Bacteria ""Thermotogae"" Thermotogae Thermotogal...",16,MID9,Control 2,stool
2393,"Bacteria ""Verrucomicrobia"" Opitutae Opitutales...",1,MID9,Control 2,stool
2394,Bacteria Cyanobacteria Cyanobacteria Chloropl...,1,MID9,Control 2,stool
2395,Bacteria Cyanobacteria Cyanobacteria Chloropl...,10,MID9,Control 2,stool

If we check the uniqueness of the index, we can see that they are unique!

In [51]:
result.index.is_unique

True

If we want to drop the "BARCODE" column we also can

In [52]:
result_without_Barcode = result.drop('BARCODE', axis=1)
result_without_Barcode

,0,1,GROUP,SAMPLE
0,"Archaea ""Crenarchaeota"" Thermoprotei Desulfuro...",7,EXTRACTION CONTROL,unknown
1,"Archaea ""Crenarchaeota"" Thermoprotei Desulfuro...",2,EXTRACTION CONTROL,unknown
2,"Archaea ""Crenarchaeota"" Thermoprotei Sulfoloba...",3,EXTRACTION CONTROL,unknown
3,"Archaea ""Crenarchaeota"" Thermoprotei Thermopro...",3,EXTRACTION CONTROL,unknown
4,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",7,EXTRACTION CONTROL,unknown
5,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",1,EXTRACTION CONTROL,unknown
6,"Archaea ""Euryarchaeota"" ""Methanomicrobia"" Meth...",1,EXTRACTION CONTROL,unknown
7,"Archaea ""Euryarchaeota"" Archaeoglobi Archaeogl...",1,EXTRACTION CONTROL,unknown
8,"Archaea ""Euryarchaeota"" Archaeoglobi Archaeogl...",1,EXTRACTION CONTROL,unknown
9,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",1,EXTRACTION CONTROL,unknown
10,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",4,EXTRACTION CONTROL,unknown
11,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",1,EXTRACTION CONTROL,unknown
12,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",2,EXTRACTION CONTROL,unknown
13,"Archaea ""Euryarchaeota"" Halobacteria Halobacte...",4,EXTRACTION CONTROL,unknown
14,"Archaea ""Euryarchaeota"" Methanococci Methanoco...",1,EXTRACTION CONTROL,unknown
15,"Archaea ""Euryarchaeota"" Methanopyri Methanopyr...",12,EXTRACTION CONTROL,unknown
16,"Archaea ""Euryarchaeota"" Thermoplasmata Thermop...",2,EXTRACTION CONTROL,unknown
17,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,unknown
18,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,unknown
19,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,unknown
20,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,unknown
21,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,unknown
22,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",53,EXTRACTION CONTROL,unknown
23,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,unknown
24,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,unknown
25,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",3,EXTRACTION CONTROL,unknown
26,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",1,EXTRACTION CONTROL,unknown
27,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",99,EXTRACTION CONTROL,unknown
28,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",17,EXTRACTION CONTROL,unknown
29,"Bacteria ""Actinobacteria"" Actinobacteria Actin...",2,EXTRACTION CONTROL,unknown
...,...,...,...,...
2366,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",10,Control 2,stool
2367,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2368,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2369,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2370,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",12,Control 2,stool
2371,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",4,Control 2,stool
2372,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",805,Control 2,stool
2373,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",862,Control 2,stool
2374,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",12,Control 2,stool
2375,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3534,Control 2,stool
2376,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",4,Control 2,stool
2377,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2378,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",25,Control 2,stool
2379,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,Control 2,stool
2380,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3,Control 2,stool
2381,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,Control 2,stool
2382,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2383,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",3,Control 2,stool
2384,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",2,Control 2,stool
2385,"Bacteria ""Proteobacteria"" Gammaproteobacteria ...",1,Control 2,stool
2386,"Bacteria ""Synergistetes"" Synergistia Synergist...",3,Control 2,stool
2387,"Bacteria ""Tenericutes"" Mollicutes Anaeroplasma...",1,Control 2,stool
2388,"Bacteria ""Tenericutes"" Mollicutes Haloplasmata...",11,Control 2,stool
2389,"Bacteria ""Thermodesulfobacteria"" Thermodesulfo...",1,Control 2,stool
2390,"Bacteria ""Thermodesulfobacteria"" Thermodesulfo...",1,Control 2,stool
2391,"Bacteria ""Thermotogae"" Thermotogae Thermotogal...",43,Control 2,stool
2392,"Bacteria ""Thermotogae"" Thermotogae Thermotogal...",16,Control 2,stool
2393,"Bacteria ""Verrucomicrobia"" Opitutae Opitutales...",1,Control 2,stool
2394,Bacteria Cyanobacteria Cyanobacteria Chloropl...,1,Control 2,stool
2395,Bacteria Cyanobacteria Cyanobacteria Chloropl...,10,Control 2,stool

## Task 3. Class War in Titanic

Use pandas to import the data file `Data/titanic.xls`. It contains data on all the passengers that travelled on the Titanic.

In [ ]:
from IPython.core.display import HTML
HTML(filename=DATA_FOLDER+'/titanic.html')

For each of the following questions state clearly your assumptions and discuss your findings:
1. Describe the *type* and the *value range* of each attribute. Indicate and transform the attributes that can be `Categorical`. 
2. Plot histograms for the *travel class*, *embarkation port*, *sex* and *age* attributes. For the latter one, use *discrete decade intervals*. 
3. Calculate the proportion of passengers by *cabin floor*. Present your results in a *pie chart*.
4. For each *travel class*, calculate the proportion of the passengers that survived. Present your results in *pie charts*.
5. Calculate the proportion of the passengers that survived by *travel class* and *sex*. Present your results in *a single histogram*.
6. Create 2 equally populated *age categories* and calculate survival proportions by *age category*, *travel class* and *sex*. Present your results in a `DataFrame` with unique index.

In [ ]:
# Write your answer here